#!/usr/bin/python
'''
Euler Project
Problem 2
http://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

sum = 2
a = 1
b = 2
val = 2
max_val = 4000000

while True:
	if a > b:
		b += a
		val = b
	else:
		a += b
		val = a

	if val > max_val:
		break
	if not val % 2:
		sum += val

print sum